export const educatorQuotes = [
  { text: "Every child deserves a champion — an adult who will never give up on them.", author: "Rita Pierson" },
  { text: "Teaching is the greatest act of optimism.", author: "Colleen Wilcox" },
  { text: "The art of teaching is the art of assisting discovery.", author: "Mark Van Doren" },
  { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "W.B. Yeats" },
  { text: "A good teacher can inspire hope, ignite the imagination, and instill a love of learning.", author: "Brad Henry" },
  { text: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
  { text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
  { text: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
  { text: "The best teachers are those who show you where to look but don't tell you what to see.", author: "Alexandra K. Trenfor" },
  { text: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
  { text: "Tell me and I forget, teach me and I may remember, involve me and I learn.", author: "Benjamin Franklin" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.", author: "William Arthur Ward" },
  { text: "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.", author: "Albert Einstein" },
  { text: "The influence of a good teacher can never be erased.", author: "Unknown" },
  { text: "Teachers affect eternity; no one can tell where their influence stops.", author: "Henry Adams" },
  { text: "A teacher takes a hand, opens a mind, and touches a heart.", author: "Unknown" },
  { text: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C.S. Lewis" },
  { text: "Teaching kids to count is fine, but teaching them what counts is best.", author: "Bob Talbert" },
  { text: "Better than a thousand days of diligent study is one day with a great teacher.", author: "Japanese Proverb" },
  { text: "What a teacher is, is more important than what he teaches.", author: "Karl Menninger" },
  { text: "The dream begins with a teacher who believes in you.", author: "Dan Rather" },
  { text: "Nine-tenths of education is encouragement.", author: "Anatole France" },
  { text: "Good teaching is one-fourth preparation and three-fourths theater.", author: "Gail Godwin" },
  { text: "A great schedule is the invisible foundation of a thriving school.", author: "Specialist Ops!" },
  { text: "When specialists thrive, students flourish.", author: "Specialist Ops!" },
  { text: "Structure gives freedom — a well-built schedule lets creativity soar.", author: "Specialist Ops!" },
  { text: "Planning today creates possibilities tomorrow.", author: "Specialist Ops!" },
  { text: "Every minute of planning time is an investment in student success.", author: "Specialist Ops!" },
  { text: "The best schedules are built with teachers, not just for them.", author: "Specialist Ops!" },
  { text: "Technology should simplify, not complicate — that's our promise.", author: "Specialist Ops!" },
  { text: "Behind every smooth school day is a brilliant schedule.", author: "Specialist Ops!" },
  { text: "Equity in scheduling means every student gets access to every opportunity.", author: "Specialist Ops!" },
  { text: "Your schedule just got a whole lot smarter.", author: "Specialist Ops!" },
  { text: "Great schools don't happen by accident. They're scheduled.", author: "Specialist Ops!" },
  { text: "One small change in a schedule can transform a teacher's entire week.", author: "Specialist Ops!" },
  { text: "Collaboration starts with time — let's make sure you have it.", author: "Specialist Ops!" },
  { text: "You just saved hours of scheduling. Go do something amazing.", author: "Specialist Ops!" },
  { text: "The only thing better than a perfect schedule is one that adapts.", author: "Specialist Ops!" },
  { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "The purpose of education is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
  { text: "If you are planning for a year, sow rice; for a decade, plant trees; for a lifetime, educate people.", author: "Chinese Proverb" },
  { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
  { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "To teach is to learn twice over.", author: "Joseph Joubert" },
  { text: "What we want is to see the child in pursuit of knowledge, and not knowledge in pursuit of the child.", author: "George Bernard Shaw" },
];

export function getRandomQuote() {
  return educatorQuotes[Math.floor(Math.random() * educatorQuotes.length)];
}
