import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

export interface PrepRow {
  question: string;
  answer?: string | null;
}

interface Props {
  schoolName?: string;
  rows: PrepRow[];
}

const styles = StyleSheet.create({
  page: { paddingTop: 36, paddingBottom: 40, paddingHorizontal: 36, fontSize: 10, fontFamily: 'Helvetica' },
  header: { marginBottom: 16, paddingBottom: 8, borderBottom: '1pt solid #1B2A4A' },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: '#1B2A4A' },
  subtitle: { fontSize: 9, color: '#555', marginTop: 4 },
  table: { borderTop: '1pt solid #1B2A4A', borderLeft: '1pt solid #1B2A4A' },
  thead: { flexDirection: 'row', backgroundColor: '#1B2A4A' },
  th: { padding: 6, fontFamily: 'Helvetica-Bold', color: '#fff', fontSize: 10, borderRight: '1pt solid #fff' },
  thAsk: { width: '45%' },
  thAns: { width: '55%' },
  row: { flexDirection: 'row', borderBottom: '1pt solid #1B2A4A', minHeight: 40 },
  rowAlt: { backgroundColor: '#FBF7EE' },
  cellAsk: { width: '45%', padding: 6, borderRight: '1pt solid #1B2A4A', fontSize: 10, color: '#1B2A4A', fontFamily: 'Helvetica-Bold' },
  cellAns: { width: '55%', padding: 6, borderRight: '1pt solid #1B2A4A', fontSize: 10, color: '#222' },
  footer: { marginTop: 16, fontSize: 8, color: '#888', fontStyle: 'italic' },
});

const CoordinatorPrepDoc = ({ schoolName, rows }: Props) => (
  <Document>
    <Page size="LETTER" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Coordinator Prep — Intake Sheet</Text>
        <Text style={styles.subtitle}>
          {schoolName ? `${schoolName} • ` : ''}Fill this out before the Setup Wizard. Answers can be transferred into the app for quick prefill.
        </Text>
      </View>

      <View style={styles.table}>
        <View style={styles.thead}>
          <Text style={[styles.th, styles.thAsk]}>Ask</Text>
          <Text style={[styles.th, styles.thAns]}>Answer</Text>
        </View>
        {rows.map((r, i) => (
          <View key={i} style={[styles.row, i % 2 === 1 ? styles.rowAlt : {}]} wrap={false}>
            <Text style={styles.cellAsk}>{r.question}</Text>
            <Text style={styles.cellAns}>{r.answer && r.answer.trim() ? r.answer : '\u00A0'}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        Generated by Specialist Ops! • GoToSpecialClass
      </Text>
    </Page>
  </Document>
);

export default CoordinatorPrepDoc;
