import { View, Text, Image, StyleSheet } from "@react-pdf/renderer";
import logoAsset from "@/assets/logo.png.asset.json";

// react-pdf needs an absolute URL for Image src in the browser.
const LOGO_URL = (() => {
  if (typeof window !== "undefined" && window.location?.origin) {
    return new URL(logoAsset.url, window.location.origin).toString();
  }
  return logoAsset.url;
})();

const C = {
  ink: "#1B2A4A",
  gold: "#C5A55A",
  mute: "#6b7280",
  band: "#FBF5E6",
};

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    borderBottom: `1.5pt solid ${C.gold}`,
    paddingBottom: 8,
    marginBottom: 10,
  },
  logo: { width: 32, height: 32, marginRight: 10 },
  titleBlock: { flex: 1 },
  title: { fontSize: 14, fontFamily: "Helvetica-Bold", color: C.ink },
  subtitle: {
    fontSize: 7.5,
    color: C.mute,
    marginTop: 2,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  meta: { fontSize: 8.5, color: C.ink, textAlign: "right", lineHeight: 1.4 },
  metaLabel: { color: C.mute },
  footer: {
    position: "absolute",
    left: 24,
    right: 24,
    bottom: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: `1pt solid ${C.gold}`,
    paddingTop: 5,
    fontSize: 7.5,
    color: C.ink,
  },
  footerCenter: { color: C.mute },
});

interface HeaderProps {
  title: string;
  subtitle?: string;
  schoolName?: string;
  schoolYear?: string;
}

export const BrandHeader = ({ title, subtitle, schoolName, schoolYear }: HeaderProps) => (
  <View style={styles.header} fixed>
    <Image src={LOGO_URL} style={styles.logo} />
    <View style={styles.titleBlock}>
      <Text style={styles.title}>{title}</Text>
      {subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}
    </View>
    <View style={styles.meta}>
      {schoolName && (
        <Text>
          <Text style={styles.metaLabel}>School: </Text>
          {schoolName}
        </Text>
      )}
      {schoolYear && (
        <Text>
          <Text style={styles.metaLabel}>Year: </Text>
          {schoolYear}
        </Text>
      )}
    </View>
  </View>
);

export const BrandFooter = () => (
  <View style={styles.footer} fixed>
    <Text>www.GoToSpecialClass.com</Text>
    <Text style={styles.footerCenter}>
      Generated by Specialist Ops!  ♥  Next Specials Class
    </Text>
    <Text>info@GoToSpecialClass.com</Text>
  </View>
);

export const BRAND_COLORS = C;
