// PDF theme — the brand identity for every @react-pdf document, derived from the
// ONE source of truth (src/brand/brand.ts). All PDFs consume THIS (never inline
// hexes), so a color/subject/name is identical on screen, in xlsx, and on paper.

import { BRAND, BRAND_HEX, subjectColorsFor } from "@/brand/brand";

export const PDF = {
  ink: BRAND_HEX.ink,
  navy: BRAND_HEX.navy,
  gold: BRAND_HEX.gold,
  goldDeep: BRAND_HEX.goldDeep,
  cream: BRAND_HEX.cream,
  band: BRAND_HEX.cream,
  paper: BRAND_HEX.paper,
  mute: BRAND_HEX.mute,
  gridline: BRAND_HEX.gridline,
  border: BRAND_HEX.gridline,
  // A hair lighter than the gridline — subtle inner dividers on paper.
  borderLight: "#E6E8EE",
  zebra: BRAND_HEX.zebra,
  white: BRAND_HEX.white,
  font: BRAND.typography.pdfSans,
  fontBold: BRAND.typography.pdfSansBold,
} as const;

/** Product identity strings for headers/footers. */
export const PDF_BRAND = {
  name: BRAND.name,
  tagline: BRAND.tagline,
  domain: BRAND.domain,
  footerTag: `Generated by ${BRAND.name}`,
} as const;

/** Subject → {accent, light} hex, from the shared brand subject band. */
export function pdfSubjectColors(subject?: string | null): { accent: string; light: string } {
  const c = subjectColorsFor(subject);
  return { accent: c.accentHex, light: c.fillHex };
}
