// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-schools.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_schools_default = defineTool({
  name: "list_schools",
  title: "List schools",
  description: "List every school in workspaces the signed-in user belongs to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("schools").select("id, name, workspace_id, grades_served, start_time, end_time").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { schools: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-teachers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_teachers_default = defineTool2({
  name: "list_teachers",
  title: "List classroom teachers",
  description: "List all classroom teachers for a school by school_id.",
  inputSchema: {
    school_id: z.string().uuid().describe("The school id to list teachers for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ school_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("classroom_teachers").select("id, name, grade, room, weekly_planning_minutes, am_pm_preference, day_preference").eq("school_id", school_id).order("grade").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { teachers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-specialists.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_specialists_default = defineTool3({
  name: "list_specialists",
  title: "List specialists",
  description: "List all specialists (art, music, PE, library, etc.) for a school.",
  inputSchema: {
    school_id: z2.string().uuid().describe("The school id to list specialists for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ school_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("specialists").select("*").eq("school_id", school_id).order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { specialists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-schedule.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_schedule_default = defineTool4({
  name: "get_schedule",
  title: "Get current schedule",
  description: "Return the schedule blocks (day, time, subject, teacher, specialist, grade, room) from the most recent generation for a school. Optionally pass generation_id to fetch a specific one.",
  inputSchema: {
    school_id: z3.string().uuid().describe("The school id."),
    generation_id: z3.string().uuid().optional().describe("Optional specific schedule_generations.id. Defaults to the latest for the school.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ school_id, generation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let genId = generation_id;
    if (!genId) {
      const { data: gen, error: gerr } = await sb.from("schedule_generations").select("id").eq("school_id", school_id).order("created_at", { ascending: false }).limit(1).maybeSingle();
      if (gerr) return { content: [{ type: "text", text: gerr.message }], isError: true };
      if (!gen) {
        return {
          content: [{ type: "text", text: "No schedule has been generated for this school yet." }],
          structuredContent: { generation_id: null, blocks: [] }
        };
      }
      genId = gen.id;
    }
    const { data, error } = await sb.from("schedule_blocks").select("day_of_week, start_time, end_time, subject, grade, room, week_label, teacher_id, specialist_id").eq("generation_id", genId).order("day_of_week").order("start_time");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ generation_id: genId, blocks: data ?? [] }, null, 2) }],
      structuredContent: { generation_id: genId, blocks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xfvablheccsoskokihkf";
var mcp_default = defineMcp({
  name: "next-specials-class-mcp",
  title: "Next Specials Class",
  version: "0.1.0",
  instructions: "Read-only access to a school's Next Specials Class data: schools, classroom teachers, specialists, and the current generated schedule. Start with list_schools to discover the school_id, then pass it to list_teachers, list_specialists, or get_schedule.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_schools_default, list_teachers_default, list_specialists_default, get_schedule_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
