// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare const __SUPABASE_URL_FALLBACK__: string;
declare const __SUPABASE_PUBLISHABLE_KEY_FALLBACK__: string;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || __SUPABASE_URL_FALLBACK__;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || __SUPABASE_PUBLISHABLE_KEY_FALLBACK__;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
